import type {Metadata} from 'next'
import './globals.css'
import '/src/styles/custom_theme.scss';
import "/src/styles/theme.scss";
import {Button} from "primereact/button";
import React from "react";
import Footer from "@/app/footer/page";
import Link from "next/link";


export const metadata: Metadata = {
    title: 'Infomover - Technologies',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        {children}
        <Footer/>
        </body>
        </html>
    )
}
