import type {Metadata} from 'next'
import {Inter, Poppins} from 'next/font/google'
import './globals.css'
import '/src/styles/custom_theme.scss';
import "/src/styles/theme.scss";

const inter = Inter({subsets: ['latin']})
const poppins = Poppins({subsets: ['devanagari'], weight: ["100", "200", "300", "400", "500", "600", "700", "800"]})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={poppins.className}>{children}</body>
        </html>
    )
}
